### ISSUE TITLE
Nomad doesn't sync AD password after update to ventura

### ISSUE THREAD

**Issue by sugita01** [jamf/NoMAD-2#4]
I initially create a post in the jamf community about this issue.
https://community.jamf.com/t5/jamf-pro/nomad-doesnt-sync-ad-password-after-update-to-ventura/m-p/284898#M255739

and someone from the community is saying that nomad is end of support???
Is this true?

**Comment by mani2care** [comment]
There is no support from team ?

**Comment by sugita01** [comment]
jamf said because its an open source product - they do not support this. they recommend me jamf connect which is about $2.50 per user per month
